author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /afa-test
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - openseadragon.min.js
    - openseadragon-svg-overlay.js
    - text-annotations.js
    - viewer.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.io/iiif/2/2r6j96bm_Tributaries-14-000.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 1800
    width: 2700
permalink: pretty
publication_info:
  date: '2022'
  editors: []
  title: Tributaries, Issue 14
show_annotation_author: true
source_info:
  title: Tributaries, Issue 14
  via_readux: true
tagline: an annotated digital edition
title: Tributaries, Issue 14
url: https://sarepal.github.io
version: 0.7
